version: "3.8"
services:
  webserver:
    build:
      context: .
      dockerfile: DockerFileDev
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"

networks:
  default:
    name: city-list-app_city-list-app-network
    external: true